notifications:
  email:
    on_success: always
    on_failure: never

language: cpp
compiler: gcc

install:
  - sudo apt-get install arduino
  - MYGIT=${PWD}
  - echo $MYGIT
  - echo $WORKPATH
  - cd ..
  - git clone git://github.com/amperka/ino.git
  - cd ino
  - sudo make install
  - sudo easy_install `cat requirements.txt`
  - cd ..
  - cd $MYGIT 

script: 
  - ino build
  - if [ -f .build/uno/firmware.hex ]; then return 0; else return 1; fi
