language: cpp
compiler: gcc

install:
  - sudo apt-get install arduino
  - BASE=${PWD##*/}
  - DIR=${PWD%$BASE}
  - cd ..
  - git clone git://github.com/amperka/ino.git
  - cd ino
  - sudo make install
  - sudo easy_install `cat requirements.txt`
  - cd ..
  - cd $DIR
  - echo PWD
  

script: 
  - ino build
  - if [ -f .build/uno/firmware.hex ]; then return 0; else return 1; fi
